import type { NextPage } from 'next'
import Head from 'next/head'
import { BaseLayout } from 'components/BaseLayout'
import { Card } from 'components/Card'
import { ChangeRate } from 'components/ChangeRate'
import { Container } from 'components/Container'
import { Hero } from 'components/Hero'
import { Icon } from 'components/Icon'
import { LayoutedContent } from 'components/LayoutedContent'
import { List } from 'components/List'
import { ListItem } from 'components/ListItem'

import styles from './home.module.css'
import React from 'react'

const Home: NextPage = () => {
  return (
    <BaseLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <Container>
          <h1>CHSB Performance Metrics</h1>
          <p className={styles.Lead}>
            Deep-dive into the statistics of CHSB and understand the mechanics of the full SwissBorg Ecosystem.
          </p>
          <Card
            header={(
              <ChangeRate
                currencyFrom="USD"
                currencyTo="CHSB"
                text="USD 0.213"
                percentage="-4.8% 24Hours"
              />
            )}
          />
          <Icon name="arrow-down" />
        </Container>
      </Hero>
      <Container>
        <h2>A breakdown of CHSB&rsquo;s circulating supply</h2>
        <LayoutedContent mobileInverted>
          <List>
            <ListItem
              iconName="supply"
              label="Remaining circulating supply"
              text="626,112,442"
            />
            <ListItem
              iconName="diamond"
              label="CHSB Staked"
              text={(
                <React.Fragment>
                  <p className='Sub-headline'>76,675,000</p>
                  <p>(<b>10.75%</b> of Circulating supply)</p>
                </React.Fragment>
              )}
            />
            <ListItem
              iconName="yield"
              label="CHSB in Smart Yield"
              text={(
                <>
                  <p className='Sub-headline'>76,675,000</p>
                  <p>(<b>10.75%</b> of Circulating supply)</p>
                </>
              )}
            />
            <ListItem
              iconName="burned"
              label="Circulating supply burned"
              text="2,416,345"
            />
            <ListItem
              iconName="buyback"
              label="CHSB in buyback pool"
              text="13,456"
            />
          </List>
        </LayoutedContent>
      </Container>
    </BaseLayout>
  )
}

export default Home
