import type { NextPage } from 'next'
import Head from 'next/head'
import { BaseLayout } from 'components/BaseLayout'
import { Card } from 'components/Card'
import { ChangeRate } from 'components/ChangeRate'
import { LayoutedContent } from 'components/LayoutedContent'
import { Hero } from 'components/Hero'
import { Icon } from 'components/Icon'

import styles from './home.module.css'

const Home: NextPage = () => {
  return (
    <BaseLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <h1>CHSB Performance Metrics</h1>
        <p className={styles.Lead}>
          Deep-dive into the statistics of CHSB and understand the mechanics of the full SwissBorg Ecosystem.
        </p>
        <Card
          header={(
            <ChangeRate
              currencyFrom="USD"
              currencyTo="CHSB"
              text="USD 0.213"
              percentage="-4.8% 24Hours"
            />
          )}
        />
        <Icon name="ArrowDown" />
      </Hero>
      <section>
        <h2>A breakdown of CHSB&rsquo;s circulating supply</h2>
        <LayoutedContent mobileInverted></LayoutedContent>
      </section>
    </BaseLayout>
  )
}

export default Home
